name: Build setup
description: Build setup

inputs:
  node-version:
    description: 'Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.'
    required: false
  node-version-file:
    description: 'File containing the version Spec of the version to use. Default: .nvmrc'
    default: .nvmrc
    required: false

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        node-version-file: ${{ inputs.node-version-file }}
        cache: pnpm

    - name: Show tool versions
      shell: bash
      run: |
        echo "Current Node.js version: $(node -v)"
        echo "Current npm version: $(npm -v)"
        echo "Current pnpm version: $(pnpm -v)"

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install
      env:
        HUSKY: 0
