name: Example Page

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]
        pnpm: [8]

    steps:
    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Install pnpm
      uses: pnpm/action-setup@v3.0.0
      with:
        version: ${{ matrix.pnpm }}

    - name: Setup Node.js ${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
        registry-url: https://registry.npmmirror.com/
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Build Project
      run: pnpm build:examples

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./dist
        publish_branch: gh-pages  # deploying branch